2022-04-10 14:44:12,450 ERROR: Exception on /Graph1 [GET] [in /home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/app/routes.py", line 46, in graph1
    return render_template('graph.html', graphJSON=graphJSON, title='Graph')
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: graph.html
2022-04-10 14:47:23,599 INFO: App startup [in /home/dh_5ejt8t/dev.project.runningdigitally.com/app/__init__.py:59]
2022-04-10 14:47:35,838 ERROR: Exception on /Graph1 [GET] [in /home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/app/routes.py", line 46, in graph1
    return render_template('graph.html', graphJSON=graphJSON1, title='Graph')
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: graph.html
2022-04-10 14:47:44,272 ERROR: Exception on /Graph1 [GET] [in /home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/app/routes.py", line 46, in graph1
    return render_template('graph.html', graphJSON=graphJSON1, title='Graph')
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/dh_5ejt8t/dev.project.runningdigitally.com/venv2/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: graph.html
2022-04-10 14:49:12,622 INFO: App startup [in /home/dh_5ejt8t/dev.project.runningdigitally.com/app/__init__.py:59]
